### ISSUE TITLE
"project" is NOT an ASAP_CRN defined value.  -> "team", "dataset"

### ISSUE THREAD

**Issue by ergonyc** [ASAP-CRN/pmdbs-sc-rnaseq-wf#66]
"project" is input to the workflow to distinguish which dataset the samples belong to.  

recommend:
- [x]  change project -> team as argument as the project currently is encoded as "team-<team>" 
- [x] add dataset as argument. 
- [x] update the adata.obs as:
    - team (instead of project)
    - dataset (addition)
    - batch_id = f"{args.team}_{args.dataset}_{args.batch}" 

- [x] update wdl to reflect these changes

We should be doing batch correction _sample_-wise.  So the batch_id won't matter.  But "team"+"dataset"+batch" should be unique, in case we want to do multi-level correction, or batch-level correction.

**Comment by ergonyc** [comment]
@kfang4 "project" has a clear use / meaning at the wdl and bucket level.  I'll leave it to you how to manage the arguments at the wdl level

**Comment by kfang4** [comment]
Correct. In WDL, project is essentially team+dataset.
