### ISSUE TITLE
make "Fixed" parameters for each script clear

### ISSUE THREAD

**Issue by ergonyc** [ASAP-CRN/pmdbs-sc-rnaseq-wf#67]
There are hard-coded values as arguments in the scripts.  Eventually we may want to make these args / parameters to the script, but for now moving the definitions to the top (after `parser.parse_args()`) should clarify

**Comment by kfang4** [comment]
Note for future changes: if there are defaults, it can be passed as a WDL argument for clarification, rather than it being hard-coded in the scripts.
