### ISSUE TITLE
 update to clustering_umap.py to curate additional leiden clusters at multiple resolutions.

### ISSUE THREAD

**Issue by ergonyc** [ASAP-CRN/pmdbs-sc-rnaseq-wf#71]
This is a punt on #63 .

Update script  to do leiden at 4 resolutions -- [0.05, 0.1, 0.2, 0.4] -- in order to enable _post-hoc_ cell-typing.

**Comment by ergonyc** [comment]
full path to scripts in docker/scvi/scripts/clustering_umap.py

**Comment by kfang4** [comment]
[clustering_umap.py](https://github.com/ASAP-CRN/pmdbs-sc-rnaseq-wf/blob/740c46b3074b2f60f1e36101d618bba49780e8cf/docker/scvi/scripts/main/clustering_umap.py#L10).
