### ISSUE TITLE
pre- and post- filtering metadata capture

### ISSUE THREAD

**Issue by ergonyc** [ASAP-CRN/pmdbs-sc-rnaseq-wf#72]
In 'merge_and_plot_qc.py' dump the metadata to something like "initial_metadata.csv"

move post- metadata dump from 'annotate_cells.py' to 'add_harmony.py'

implications:  
- [ ] output_metadat_file arguments need to be _removed_ from 'annotate_cells.py' and csv dump removed
- [ ] output_metadat_file arguments need to be _added_ to 'add_harmony.py' and csv dump added
    - note: UMAP_1 and UMAP_2 to be added before dump (but not duplaced in adata.obs)
- [ ] output_metadat_file arguments need to be _added_ to 'merge_and_plot_qc.py' and csv dump added
- [ ] wdl calls to "merge_and_plot_qc.py" and "add_harmony.py" need to include  "--output-metadata-file" args

**Comment by ergonyc** [comment]
full path to scripts in docker/scvi/scripts/

**Comment by kfang4** [comment]
Initial metadata is now outputted in [cohort_analysis.wdl](https://github.com/ASAP-CRN/pmdbs-sc-rnaseq-wf/blob/740c46b3074b2f60f1e36101d618bba49780e8cf/workflows/cohort_analysis/cohort_analysis.wdl).
