### ISSUE TITLE
scib-metrics report not exported?

### ISSUE THREAD

**Issue by ergonyc** [ASAP-CRN/pmdbs-sc-rnaseq-wf#73]
in the artifact_metrics.py script we create two reports: 

1. a graphical report table and
2. a csv summary

These are both written to a folder defined by the --output-report-dir argument.   The `scib-metrics` library hard codes the report to be "scib_results.svg" in that directory.

We should export both the .csv and .svg, with tehe appropriate cohort_id prepended.

**Comment by ergonyc** [comment]
#75 and #74  should address this.

**Comment by kfang4** [comment]
[Fix in cohort_analysis.wdl](https://github.com/ASAP-CRN/pmdbs-sc-rnaseq-wf/blob/df6c280fb1fe5d565e8fa20ba49390d98897368d/workflows/cohort_analysis/cohort_analysis.wdl#L390-L391).
